### ISSUE TITLE
We need to update our documentation for the path argument

### ISSUE THREAD

**Issue by mgrover1** [ncar-xdev/ecgtools#143]
### What happened?

As of the latest versions of ecgtools, the input for path is a list of strings. This is not clear in the docs.

### What did you expect to happen?

We should have examples that line up with the validation.

### Minimal Complete Verifiable Example

```python
ecgtools.Builder(paths=['some_path'])
```

**Comment by Thomas-Moore-Creative** [comment]
Aha!  I'm following along here ( [use a custom parser](https://ecgtools.readthedocs.io/en/latest/how-to/use-a-custom-parser.html) ) and was getting confused as heck by errors.  So API changes haven't filtered through the docs yet?  BTW - fully understand how hard it is to keep useful packages rolling so, no judgement.  Thanks for `ecgtools` !

**Comment by mgrover1** [comment]
Thanks for the reminder here - this has not been reflected in the docs. A PR is welcome :)

**Comment by Thomas-Moore-Creative** [comment]
@mgrover1 - does one really want a PR from someone who is just now trying to figure out how the basics of `intake`, `intake-esm`, & 'ecgtools` works? =)

Also - thanks for being responsive!

**Comment by mgrover1** [comment]
Absolutely! Happy to provide feedback - please let me know if you have any questions about the process.

I believe [this notebook](https://github.com/ncar-xdev/ecgtools/blob/main/docs/source/how-to/use-a-custom-parser.ipynb) is the one that will need to be updated.

**Comment by Thomas-Moore-Creative** [comment]
NB: I'm working on Australian HPC so I'm not following the example exactly as I don't have GLADE access.  But will give it a go, thanks @mgrover1

**Comment by Thomas-Moore-Creative** [comment]
@mgrover1 I made two very, very simple syntax changes that allowed me to run these lines in my workflow ( where before they failed )

`b = Builder(['/glade/p/cesm/amwg/amwg_diagnostics/obs_data'])`

`b.build(parsing_func = parse_amwg_obs)`

As noted I can't run the GLADE based code.

PR subbed.
