### ISSUE TITLE
Release v2023.7.??

### ISSUE THREAD

**Issue by dougiesquire** [ncar-xdev/ecgtools#165]
A few changes have been made recently to deal with updates in dependencies (see #162, #164). We should do a release that includes these. This should be done at the same time as a new Intake-ESM release, since ecgtools and Intake-ESM depend on one another and both have unreleased changes to support pydantic v2.

**Comment by mgrover1** [comment]
I can cut a release now - @dougiesquire are you interested in joining the maintainers team for both ecgtools/intake-esm? I appreciate all the help here!

**Comment by mgrover1** [comment]
New releases have been added for both ecgtools + intake-esm

**Comment by dougiesquire** [comment]
> are you interested in joining the maintainers team for both ecgtools/intake-esm?

@dcherian already added me as a maintainer to ecgtools a few days ago. Happy to also help out with intake-esm where I can.
